export const doctors = [
    {
        id: 1,
        name: "Dr. Ayesha Khan",
        specialization: "Cardiologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/028/287/555/small_2x/an-indian-young-female-doctor-isolated-on-green-ai-generated-photo.jpg",
        timing: "9:00 AM - 1:00 PM",
        aboutDoctor: "Experienced cardiologist with 10+ years in diagnosing and treating heart conditions.",
        available: true,
    },
    {
        id: 2,
        name: "Dr. Ali Raza",
        specialization: "Dermatologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/029/527/656/small_2x/portrait-of-a-confident-male-doctor-isolated-on-white-background-free-photo.jpg",
        timing: "10:00 AM - 2:00 PM",
        aboutDoctor: "Specialist in skincare, treating common and rare dermatological conditions.",
        available: true,
    },
    {
        id: 3,
        name: "Dr. Maria Siddiqui",
        specialization: "Pediatrician",
        image: "https://static.vecteezy.com/system/resources/thumbnails/030/101/689/small_2x/female-doctor-posing-in-a-hospital-corridor-free-photo.jpg",
        timing: "11:00 AM - 3:00 PM",
        aboutDoctor: "Dedicated pediatrician with expertise in child health and development.",
        available: true,
    },
    {
        id: 4,
        name: "Dr. Faisal Qureshi",
        specialization: "Orthopedic Surgeon",
        image: "https://static.vecteezy.com/system/resources/thumbnails/027/865/432/small_2x/a-smiling-young-male-doctor-wearing-glasses-isolated-on-white-background-free-photo.jpg",
        timing: "8:00 AM - 12:00 PM",
        aboutDoctor: "Experienced in treating bone and joint issues with minimally invasive procedures.",
        available: false,
    },
    {
        id: 5,
        name: "Dr. Sana Ahmed",
        specialization: "Gynecologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/028/227/444/small_2x/smiling-female-doctor-in-a-hospital-free-photo.jpg",
        timing: "12:00 PM - 4:00 PM",
        aboutDoctor: "Expert in women's health, including pregnancy and reproductive care.",
        available: true,
    },
    {
        id: 6,
        name: "Dr. Omar Hassan",
        specialization: "Neurologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/027/865/430/small_2x/a-young-male-doctor-smiling-and-standing-in-his-office-free-photo.jpg",
        timing: "9:00 AM - 12:00 PM",
        aboutDoctor: "Specialized in treating neurological disorders like epilepsy and migraines.",
        available: true,
    },
    {
        id: 7,
        name: "Dr. Iqra Javed",
        specialization: "Endocrinologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/030/122/002/small_2x/young-female-doctor-smiling-in-a-clinic-free-photo.jpg",
        timing: "2:00 PM - 6:00 PM",
        aboutDoctor: "Treats hormone-related disorders, including diabetes and thyroid issues.",
        available: false,
    },
    {
        id: 8,
        name: "Dr. Ahmed Khan",
        specialization: "Gastroenterologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/027/850/659/small_2x/a-smiling-male-doctor-wearing-glasses-standing-in-his-office-free-photo.jpg",
        timing: "1:00 PM - 5:00 PM",
        aboutDoctor: "Expert in digestive health and gastrointestinal diseases.",
        available: true,
    },
    {
        id: 9,
        name: "Dr. Fatima Malik",
        specialization: "Psychiatrist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/028/234/567/small_2x/smiling-female-psychiatrist-posing-in-her-office-free-photo.jpg",
        timing: "10:00 AM - 1:00 PM",
        aboutDoctor: "Provides counseling and treatment for mental health disorders.",
        available: true,
    },
    {
        id: 10,
        name: "Dr. Bilal Sheikh",
        specialization: "General Physician",
        image: "https://static.vecteezy.com/system/resources/thumbnails/029/543/879/small_2x/a-young-general-physician-smiling-in-the-clinic-free-photo.jpg",
        timing: "3:00 PM - 8:00 PM",
        aboutDoctor: "Expert in diagnosing and treating common medical conditions.",
        available: true,
    },
    {
        id: 11,
        name: "Dr. Ayesha Khan",
        specialization: "Cardiologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/028/287/555/small_2x/an-indian-young-female-doctor-isolated-on-green-ai-generated-photo.jpg",
        timing: "9:00 AM - 1:00 PM",
        aboutDoctor: "Experienced cardiologist with 10+ years in diagnosing and treating heart conditions.",
        available: true,
    },
    {
        id: 12,
        name: "Dr. Ali Raza",
        specialization: "Dermatologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/029/527/656/small_2x/portrait-of-a-confident-male-doctor-isolated-on-white-background-free-photo.jpg",
        timing: "10:00 AM - 2:00 PM",
        aboutDoctor: "Specialist in skincare, treating common and rare dermatological conditions.",
        available: true,
    },
    {
        id: 13,
        name: "Dr. Maria Siddiqui",
        specialization: "Pediatrician",
        image: "https://static.vecteezy.com/system/resources/thumbnails/030/101/689/small_2x/female-doctor-posing-in-a-hospital-corridor-free-photo.jpg",
        timing: "11:00 AM - 3:00 PM",
        aboutDoctor: "Dedicated pediatrician with expertise in child health and development.",
        available: true,
    },
    {
        id: 14,
        name: "Dr. Faisal Qureshi",
        specialization: "Orthopedic Surgeon",
        image: "https://static.vecteezy.com/system/resources/thumbnails/027/865/432/small_2x/a-smiling-young-male-doctor-wearing-glasses-isolated-on-white-background-free-photo.jpg",
        timing: "8:00 AM - 12:00 PM",
        aboutDoctor: "Experienced in treating bone and joint issues with minimally invasive procedures.",
        available: false,
    },
    {
        id: 15,
        name: "Dr. Sana Ahmed",
        specialization: "Gynecologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/028/227/444/small_2x/smiling-female-doctor-in-a-hospital-free-photo.jpg",
        timing: "12:00 PM - 4:00 PM",
        aboutDoctor: "Expert in women's health, including pregnancy and reproductive care.",
        available: true,
    },
    {
        id: 16,
        name: "Dr. Omar Hassan",
        specialization: "Neurologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/027/865/430/small_2x/a-young-male-doctor-smiling-and-standing-in-his-office-free-photo.jpg",
        timing: "9:00 AM - 12:00 PM",
        aboutDoctor: "Specialized in treating neurological disorders like epilepsy and migraines.",
        available: true,
    },
    {
        id: 17,
        name: "Dr. Iqra Javed",
        specialization: "Endocrinologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/030/122/002/small_2x/young-female-doctor-smiling-in-a-clinic-free-photo.jpg",
        timing: "2:00 PM - 6:00 PM",
        aboutDoctor: "Treats hormone-related disorders, including diabetes and thyroid issues.",
        available: false,
    },
    {
        id: 18,
        name: "Dr. Ahmed Khan",
        specialization: "Gastroenterologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/027/850/659/small_2x/a-smiling-male-doctor-wearing-glasses-standing-in-his-office-free-photo.jpg",
        timing: "1:00 PM - 5:00 PM",
        aboutDoctor: "Expert in digestive health and gastrointestinal diseases.",
        available: true,
    },
    {
        id: 19,
        name: "Dr. Fatima Malik",
        specialization: "Psychiatrist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/028/234/567/small_2x/smiling-female-psychiatrist-posing-in-her-office-free-photo.jpg",
        timing: "10:00 AM - 1:00 PM",
        aboutDoctor: "Provides counseling and treatment for mental health disorders.",
        available: true,
    },
    {
        id: 20,
        name: "Dr. Bilal Sheikh",
        specialization: "General Physician",
        image: "https://static.vecteezy.com/system/resources/thumbnails/029/543/879/small_2x/a-young-general-physician-smiling-in-the-clinic-free-photo.jpg",
        timing: "3:00 PM - 8:00 PM",
        aboutDoctor: "Expert in diagnosing and treating common medical conditions.",
        available: true,
    },
    {
        id: 21,
        name: "Dr. Zainab Fatima",
        specialization: "Oncologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/028/227/002/small_2x/young-female-oncologist-in-hospital-corridor-free-photo.jpg",
        timing: "8:00 AM - 1:00 PM",
        aboutDoctor: "Specializes in cancer diagnosis and treatment plans.",
        available: false,
    },
    {
        id: 22,
        name: "Dr. Usman Javed",
        specialization: "Urologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/027/865/435/small_2x/male-doctor-in-his-clinic-free-photo.jpg",
        timing: "4:00 PM - 8:00 PM",
        aboutDoctor: "Expert in urinary tract and male reproductive health.",
        available: true,
    },
    {
        id: 23,
        name: "Dr. Hira Zaidi",
        specialization: "Radiologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/030/098/667/small_2x/female-radiologist-in-a-hospital-setting-free-photo.jpg",
        timing: "9:00 AM - 12:00 PM",
        aboutDoctor: "Specializes in medical imaging for accurate diagnosis.",
        available: true,
    },
    {
        id: 24,
        name: "Dr. Hamza Ali",
        specialization: "Pulmonologist",
        image: "https://static.vecteezy.com/system/resources/thumbnails/027/865/436/small_2x/male-doctor-holding-a-medical-chart-free-photo.jpg",
        timing: "12:00 PM - 4:00 PM",
        aboutDoctor: "Expert in respiratory system disorders.",
        available: true,
    },
    // Add 12 more doctors following the same pattern...
];

export const specializations = [
    { id: 1, specialization: "Cardiologist" },
    { id: 2, specialization: "Dermatologist" },
    { id: 3, specialization: "Pediatrician" },
    { id: 4, specialization: "Orthopedic Surgeon" },
    { id: 5, specialization: "Gynecologist" },
    { id: 6, specialization: "Neurologist" },
    { id: 7, specialization: "Endocrinologist" },
    { id: 8, specialization: "Gastroenterologist" },
    { id: 9, specialization: "Psychiatrist" },
    { id: 10, specialization: "General Physician" },
    { id: 11, specialization: "Oncologist" },
    { id: 12, specialization: "Urologist" },
    { id: 13, specialization: "Radiologist" },
    { id: 14, specialization: "Pulmonologist" },
    { id: 15, specialization: "Ophthalmologist" },
    { id: 16, specialization: "ENT Specialist" },
    { id: 17, specialization: "Nephrologist" },
    { id: 18, specialization: "Rheumatologist" },
    { id: 19, specialization: "Plastic Surgeon" },
    { id: 20, specialization: "Anesthesiologist" },
    { id: 21, specialization: "Immunologist" },
    { id: 22, specialization: "Sports Medicine Specialist" },
    { id: 23, specialization: "Infectious Disease Specialist" },
    { id: 24, specialization: "Hematologist" },
    { id: 25, specialization: "Psychologist" },
    { id: 26, specialization: "Allergist" }
];
